### ISSUE TITLE
fail the PR if minimum coverage not met

### ISSUE THREAD

**Issue by swapnilpandey03** [Madrapps/jacoco-report#21]
is there any way to fail the pr in case the minimum coverage criteria are not met?

**Comment by felipebonezi** [comment]
Is this feature in consideration?
I think this repo is abandonned...

**Comment by thsaravana** [comment]
@swapnilpandey03 There is no config within the github action to fail the PR. But the action returns two outputs "coverage-overall" and "coverage-changed-files", so you could add another step to your workflow and fail the PR based on this value. 
I am gonna close this Issue, since this is a duplicate of #10 .
